### ISSUE TITLE
ipget does not build

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/distributions#139]
```
$ make ipget
echo "** ipget **"
** ipget **
cd dists/ipget && make
../../build-go.sh ipget github.com/ipfs/ipget versions
using /ipns/dist.ipfs.io as a template.
dirty output directory
will skip building already existing binaries
to perform a fresh build, please delete ../../releases/ipget
HEAD is now at f47d88c Add license to README.
building versions: v0.0.1
v0.2.0

v0.0.1 already exists, skipping...
Building version v0.2.0 binaries
==> checking out version v0.2.0 in /Users/richard/src/ipfs/distributions/dists/ipget/gopath/src/github.com/ipfs/ipget
HEAD is now at f47d88c Add license to README.
HEAD is now at f47d88c... Add license to README.
no matrix file for version v0.2.0 found, and no 'build_matrix' detected
make[1]: *** [dist] Error 1
make: *** [ipget] Error 2
```

**Comment by RichardLitt** [comment]
@noffle Any ideas?

**Comment by noffle** [comment]
It's missing a `build_matrix` file. You should be able to just `cp releases/gx/build_matrix releases/ipget`.

After this, there will still be a number of issues. ipget depends on `fallback-ipfs-shell`, which depends on some sub-packages of go-ipfs, which haven't been available under gx, so haven't been pinned. As a result, as the API of those sub-packages changes on go-ipfs master, the ipget build breaks. In order to get a stable build for ipget we'll need to start publishing sub-packages of go-ipfs to gx for `fallback-ipfs-shell` to use.

**Comment by noffle** [comment]
For anyone interested in taking a stab at this, just clone github.com/noffle/ipfs-embedded-shell and do a `go build`: you'll see the breakages vs go-ipfs on master. You'll need to update the API calls to be consistent, and then create + publish those go-ipfs packages on gx, and add them as gx deps to ipfs-embedded-shell. You may need to repeat this process on `ipfs-fallback-shell` as well.

**Comment by gammazero** [comment]
Is this still an issue?  The original repo [github.com/whyrusleeping/ipfs-embedded-shell](https://github.com/whyrusleeping/ipfs-embedded-shell) builds after updating dependencies:
```sh
git clone git@github.com:whyrusleeping/ipfs-embedded-shell.git
cd ipfs-embedded-shell
go mod edit -droprequire=github.com/ipfs/go-ipfs
go mod tidy
go build
```
So it seems like things are fixed there, and this issue can probably be closed.

**Comment by RichardLitt** [comment]
I don't know. If that works, we're probably good. Thanks for the follow up.
