### ISSUE TITLE
Add gui-based helper apps to dist site

### ISSUE THREAD

**Issue by daviddias** [ipfs/distributions#168]
Add the helper apps (Companion, WebUI, Desktop) to the dists site so it's truly a unified place to download all the things.

> Historical reference: https://github.com/ipfs-shipyard/station/issues/508

**Comment by jessicaschilling** [comment]
If I understand correctly, the dist site add process as it currently stands will only work for Go distributions?
![image](https://user-images.githubusercontent.com/1507828/82601806-5e0ef300-9b6d-11ea-9183-0d119cf6f322.png)

This issue was to include the GUI apps (Desktop, Companion, Web UI), but in the idea of "download all the things", would assume this would extend to js-ipfs as well.

Thoughts on whether it makes sense to take this on as an effort?
cc @daviddias @Stebalien

**Comment by Stebalien** [comment]
The hope was to be able to distribute anything, but that hasn't been implemented. However, I'd love to extend it to support that in the future.

**Comment by jessicaschilling** [comment]
Would this be a suitable bounty item, maybe?

**Comment by Stebalien** [comment]
We'd have to scope and define the problem first and it's not really a high priority.
