### ISSUE TITLE
Reference for packages available in other package managers (Arch, Brew, and so on)

### ISSUE THREAD

**Issue by daviddias** [ipfs/distributions#22]
Arch - https://github.com/ipfs/go-ipfs/issues/7
Brew - https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ipfs.rb

**Comment by Dignifiedquire** [comment]
Any ideas, thoughts on how we want to pursue this? (homebrew is out of date most of the time) Do we maintain those ourselves, etc

**Comment by jbenet** [comment]
We don't yet maintain those releases. but eventually we should. I would like to have some guidelines before we take that on, for example:

- code signing (beginning to get setup for this)
- package name should include `ipfs` (eg `go-ipfs` or `ipfs-node`, or `ipfs-update` or `ipfs-fs-repo-migrations`. that way we avoid polluting the pkg mgr's namespace
- publish new updates in a timely manner (within a few days).
- maybe publish on pkg mgrs some time (a day or two) _after_ releasing, so that any bugs may be tested in the close community + fixed before being shipped out to pkg mgr end users
- standard description/readme guidelines (wording, links to ipfs, links to repos, etc)
- whether to prefer our own channels (apt ppa's, brew taps, etc) or use the main one
- enlist a single "packager" master for each of the package managers, as the point-person to review + resolve issues. 

any more ideas?

**Comment by Dignifiedquire** [comment]
Sounds good, from experience I think it's also important to make sure this process is as automated as possible and that at least 3 people know how and have rights to do it.

**Comment by Dignifiedquire** [comment]
One other note, when we have things setup with package managers we should make this prominent in the dist page, as this makes it much easier for users to keep up to date.

**Comment by jbenet** [comment]
thanks updated list above

**Comment by mitar** [comment]
Just a suggestion, don't name the package `go-ipfs`, but `ipfs-go` or something.

**Comment by ChrisChinchilla** [comment]
I have no experience of the other platform packages, but the Homebrew one has always worked for me and is up to date, and regularly updated. I'm more of a tech writer, so from a docs perspective I'd suggest adding a mention that packages are available, but they aren't officially maintained, community supported etc.

I'd be happy to add that to docs, but would like to know it's welcome before doing so. :)

**Comment by solarimix** [comment]
is the homebrew ipfs formulae still valid on Apple OSX X84_64, Mountain Lion 10.5.8 running TigerBrew?

**Comment by solarimix** [comment]
> Arch - [ipfs/go-ipfs#7](https://github.com/ipfs/go-ipfs/issues/7)
> Brew - https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ipfs.rb

https://formulae.brew.sh/formula/ipfs

**Comment by solarimix** [comment]
https://github.com/ipfs/website/issues/16

hope that helps!?

https://formulae.brew.sh/cask/ipfs
