### ISSUE TITLE
Building without downloading everything

### ISSUE THREAD

**Issue by Stebalien** [ipfs/distributions#260]
We should be rebuilding dists without downloading _everything_.

**Comment by olizilla** [comment]
it's the _building everything_ that seems to be the biggest pain here. I figure we should carve it up so that we could build / edit / improve the website without needing to download anything extra... and we should be able to add new versions or distributions without having to fetch and build the entire universe.

I'm poking around now to see if I can figure it out. I'm imagining we'd store the most recent dist.json in the repo which is needed to build the website index.html, and track latest CIDs per dist directory so that we could patch new versions in.

**Comment by olizilla** [comment]
oh i see, we only *build* everything if we can't get it from ipfs

https://github.com/ipfs/distributions/blob/211588d697902572642a53d20b2ff5d121ecd1b9/build-go.sh#L338-L340

**Comment by olizilla** [comment]
Using `ipfs get` instead of the `ipfs files cp` means we've gotta store the whole history of all dists twice.
