### ISSUE TITLE
Unsupported GOOS/GOARCH pair darwin/386

### ISSUE THREAD

**Issue by iand** [ipfs/distributions#365]
Go 1.15 dropped support for 32-bit binaries on macOS, iOS, iPadOS, watchOS, and tvOS so attempting to run `make` on a fresh clone of this repository results in failure:

```
HEAD is now at 94df8f07f version bump to 0.3.2 after mdns
go: creating new go.mod: module ipfs-distributions
go: to add module requirements and sums:
	go mod tidy
==> building for darwin 386
    output to ../../releases/go-ipfs/v0.3.2/go-ipfs_v0.3.2_darwin-386
cmd/go: unsupported GOOS/GOARCH pair darwin/386
cp: cannot stat 'go-ipfs/build-log': No such file or directory
make: *** [../../common.mk:14: dist] Error 1
```

My version of Go:
```
go version go1.16 linux/amd64
```

To avoid this we could associate versions with a maximum Go version and then issue a warning for older versions or build via docker with known Go image.

Note that this is a different issue to that discussed in https://github.com/ipfs/distributions/issues/311

**Comment by aschmahmann** [comment]
We could, although I think it's worth considering what the point is of supporting rebuilds of old binaries this way. Since #260 was resolved it's not clear to me why anyone would try and rebuild old versions of the binaries, what did you have in mind?

If the builds were reproducible I could potentially see someone trying to reproduce the website, but then what we'd be looking for is an exact version of Go and not a min/max version number. Without reproducible builds what's the point?

Note: it looks like the reason this error is showing up for early versions of go-ipfs (<=0.4.0) there were separate build matricies instead of sharing one like we've had since then. Worrying about ancient versions of go-ipfs doesn't seem worth much attention.

**Comment by iand** [comment]
I think the only reason for rebuilding older versions is if there was a backported security issue in the version of Go originally used in the build. Presumably we rebuild for each minor release of a recent Go?

**Comment by lidel** [comment]
IIUC this is no longer a problem because  Apple stopped releasing 32-bit devices back in 2011 and we removed support for it in new releases (https://github.com/ipfs/distributions/issues/311#issuecomment-662376596)
