### ISSUE TITLE
CI gets stuck due to content routing

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/distributions#392]
It seems to take well over an hour to just run, but for that to happen, the build process needs to not get stuck "comparing releases", which can happen both on the "build" and on the "persist" steps at least.

**Comment by lidel** [comment]
It happened to me too – means a problem with content  routing.
You can see below that only the first diff was slow, when go-ipfs is connected  to cluster with all content, the compare is fast.


> ![2021-08-17--22-49-51](https://user-images.githubusercontent.com/157609/129798683-b5b7288a-4fa8-4635-a89b-5e58241e2ea7.png)
> – source https://github.com/ipfs/distributions/runs/3342903957?check_suite_focus=true#step:5:1092


Not sure why this is happening – go-ipfs running on CI is  getting the list of cluster peers and pre-connecting to them, to avoid slow DHT  lookup:

https://github.com/ipfs/distributions/blob/c4cfeac1f6f518f095fee843ec2d8bf9213f3254/scripts/ci/setup-ipfs.sh#L42-L50

lmk if there is a better way to ensure there is a provider  available for bitswap

**Comment by hsanjuan** [comment]
It should probably keep connecting. Clusters may close the connections from their sides.. but yeah, I guess content-advertisement from the clusters is not really working (?).

**Comment by aschmahmann** [comment]
From the info you've posted (and probably from the GH Action) it's hard to tell what's going wrong here. Some candidates include:
- The cluster was having issues
   - The problem isn't in this repo. We can check on the health of the clusters and if they happily have and will send you the data.
- You connection got dropped by cluster
   - This probably shouldn't happen, but if you used Peering instead of `ipfs swarm connect` you'd re-attach to the cluster again
- You connections got terminated by GitHub
   - Well... it's hard to say what to do here other than try to be as little of an outlier as possible. Some examples might include:
      - Turning off the DHT entirely
      - Emptying out the bootstrap peers list
    - If it's still an issue than for debugging purposes maybe log `ipfs swarm peers` every few minutes since there should only be  a few peers listed.

**Comment by lidel** [comment]
Ack. I think the low hanging task is to

1.  refactor [manual swarm connect](https://github.com/ipfs/distributions/blob/e6a53d5af8ab8b2582c1a01cf2c4ab0f07e31696/scripts/ci/setup-ipfs.sh#L42-L50) to build and update  [peering](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#peering) section  in the go-ipfs config
2. make sure when `ipfs daemon` starts it uses updated config

**Comment by lidel** [comment]
go-ipfs 0.10.0 has `ipfs swarm peering` command which makes things easier (no need for editing config manually)
