### ISSUE TITLE
Add Universal Mac OS build

### ISSUE THREAD

**Issue by RangerMauve** [ipfs/distributions#770]
Hello, we'd like to bundle Kubo with Electron applications to run on Mac OS with Apple Silicone / x64 macs via the [npm-go-ipfs](https://github.com/ipfs/npm-go-ipfs/) module for the WebRecorder and Agregore Browser projects.

At the moment this is complicated by the fact that while Electron supports generating Universal builds for Mac OS, kubo currently requires choosing one or the other.

Would it be possible to add Universal Mac OS builds to the distribution matrix to enable this use case?

**Comment by BigLep** [comment]
2023-05-18 maintainer conversation: Brave went down the path of using separate binaries (since they want to minimize the amount they are bundling/distributing) and we expect IPFS desktop to use separate binaries.  We're not seeing the need currently.  The "wrapper app" (Brave, desktop, Electron in the original post) can bring in both binaries.

We're not sure if https://github.com/ipfs/npm-go-ipfs/ is smart enough to detect arm, but if that's the case, that should be in an issue in that repo.

The biggest value we could see in completing this is to have a single "download for MacOS" URL at https://dist.ipfs.tech/#kubo.  It has so-far worked though for users to select the right platform for themseleves.

As a result, we're not planning to fix this.  Please feel free to reopen if there are important usecases we're not accounting for.
